parameters:
  bin_dir: ./vendor/bin
  git_dir: .
  hooks_dir:
  hooks_preset: local
  tasks: []
  stop_on_failure: false
  ignore_unstaged_changes: false
  extensions: []
  ascii:
    failed: grumphp-grumpy.txt
    succeeded: grumphp-happy.txt
