#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1
DIFF=$(git diff -r -p -m -M --full-index --staged | cat)

# Copying commit message to vagrant ...
VAGRANT_COMMIT_MSG_FILE=$(vagrant ssh --command 'mktemp -t grumphp-commitmsg.XXXXXXXXXX')
vagrant ssh --command "cat > $VAGRANT_COMMIT_MSG_FILE" < $COMMIT_MSG_FILE

# Running GrumPHP
vagrant ssh --command "echo '$DIFF' | exec $(HOOK_COMMAND) '--git-user=$GIT_USER' '--git-email=$GIT_EMAIL' '$VAGRANT_COMMIT_MSG_FILE'"

# Cleaning up commit file ...
vagrant ssh --command "rm $VAGRANT_COMMIT_MSG_FILE"

# Validate exit code of above command
RC=$?
if [ "$RC" != 0 ]; then
    exit $RC;
fi

# Clean exit:
exit 0;
