#!/bin/sh

vagrant ssh --command "cd ${VAGRANT_DIR} && (exec $(HOOK_COMMAND) '--skip-success-output')"

# Validate exit code of above command
RC=$?
if [ "$RC" != 0 ]; then
    exit $RC;
fi

# Clean exit:
exit 0;
