#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git diff -r -p -m -M --full-index --staged | cat)
DIFF=$(printf %q "${DIFF}")

# Run GrumPHP
vagrant ssh --command '$(which bash)' << COMMANDS
  echo $DIFF | exec $(HOOK_COMMAND) '--ansi' '--skip-success-output'
COMMANDS

# Validate exit code of above command
RC=$?
if [ "$RC" != 0 ]; then
    exit $RC;
fi

# Clean exit:
exit 0;
